Update 2022.json
Aeroblast/book_sales_info_data pull request #14
Opened 2022-12-01 10:34 UTC by kiriairi

2022-12-01 13:23 UTC, Aeroblast requested changes

2022-12-01 13:23 UTC, Aeroblast commented on base/2022.json
> +    "sourceDesc": "[カクヨム【期間限定！①巻丸読み】](https://kakuyomu.jp/works/16816927862670243115)",
カクヨム的内容是易失的，应当用快照留档案。而且根据 [最早的记录](http://web.archive.org/web/20220426091609/https://kakuyomu.jp/works/16816927862670243115) 至少4/26就有了这个纪录。应该找到其他来源。

2022-12-01 13:23 UTC, Aeroblast commented on base/2022.json
> +    "sourceDesc": "[原作最新刊帯](https://www.shinchosha.co.jp/book/180246/)",
“最新”……可以参考wiki的标号，参考写法：シリーズの13冊目

2022-12-02 05:49 UTC, kiriairi reviewed
樱子应该就是4/26，虽然不确定官网和日亚带书腰的封面是不是也是这个日期

2022-12-02 06:01 UTC, Aeroblast commented
哦俺一开始看串日期了，那当成4/25好像也没问题。但是书腰这个不确定的话就不知道该写发售日还是可见日了。待会在issue那丢个存疑好了。

2022-12-02 06:02 UTC, merged